### ISSUE TITLE
双击系统托盘图标会误触其他按键

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [CHKZL/DDTV_Old#10]
如图，双击图标就会消失，然后系统就判定你点击了下一个图标
![GIF](https://user-images.githubusercontent.com/24391614/54426320-73f77b80-4752-11e9-8cc7-67218e6f5bec.gif)

**Comment by CHKZL** [comment]
在现在的测试版本中已经修复这个问题，添加了托盘图标右键菜单
