### ISSUE TITLE
建议增加功能：打开直播间连接

### ISSUE THREAD

**Issue by ShimotsukiH** [CHKZL/DDTV_Old#11]
现在无法看到弹幕 但是遇到神回想发发弹幕 要拿起手机或者手动打直播间地址有点慢
双击画面进入直播间可好？

**Comment by kuro00** [comment]
或者后面加个用浏览器打开的按钮？

**Comment by CHKZL** [comment]
下一个版本会增加弹幕显示功能和自动录像功能..主体功能已经完成了，在调试了

**Comment by kuro00** [comment]
加一个按钮什么的 能直接方便的过去发个弹幕什么的了
