### ISSUE TITLE
1.0.1.4主窗体上有一个意义不明的添加按钮

### ISSUE THREAD

**Issue by kuro00** [CHKZL/DDTV_Old#12]
![TIM截图20190315194018](https://user-images.githubusercontent.com/13074131/54429124-9ab9b000-475a-11e9-9d76-8da74b76f389.png)
点了之后就会报错退出

**Comment by CHKZL** [comment]
这是昨天我错误的提交了一个更新，这个错误大概持续了10分钟左右，在那10分钟内更新会出现这个问题。我发现过后马上重新提交了一次正确的。从新下载一次最新版本，替换里面的“DD监控器.exe”就行了..

**Comment by CHKZL** [comment]
> ![TIM截图20190315194018](https://user-images.githubusercontent.com/13074131/54429124-9ab9b000-475a-11e9-9d76-8da74b76f389.png)
> 点了之后就会报错退出

这是我昨天更新时使用了错误的项目，大概十分钟左右我发现了问题马上替换成正确的，在那10分钟里下载的客户端会有这个问题。
只需要下载最新版本替换里面的“DD监控器.exe”或者直接更新一次客户端就行了
