### ISSUE TITLE
1.0.1.4使用的RoomListConfig似乎与之前版本的不通用

### ISSUE THREAD

**Issue by LzNOHentai** [CHKZL/DDTV_Old#13]
直接使用无法读取出列表，看了一下ini内字段有改变，1.0.1.4生成的ini多了"Types":bilibili，原本的Ty改成了status，我个人是正则表达式整体修改过后可以正常读取列表。

**Comment by CHKZL** [comment]
在1.3到1.4版本的时候进行了大量的代码规范化和重命名...在批量修改的时候把配置文件一起修改了没有发现。以后不会发生这种问题了....

**Comment by CHKZL** [comment]
最新的一次更新解决了这个问题，兼容的老版本的文件
