### ISSUE TITLE
功能改进意见 :房间号输入框识别连接

### ISSUE THREAD

**Issue by ShimotsukiH** [CHKZL/DDTV_Old#14]
现在只能识别房间号 每次都得手动删减 有麻烦啊
能不能直接识别连接 软件自己减去多余信息呢……
当然能直接抓到房间名是坠吼的
谢谢
![GIF](https://user-images.githubusercontent.com/33424662/54470888-ec118000-47ea-11e9-95ed-901a082404ef.gif)

**Comment by CHKZL** [comment]
> 现在只能识别房间号 每次都得手动删减 有麻烦啊
> 能不能直接识别连接 软件自己减去多余信息呢……
> 当然能直接抓到房间名是坠吼的
> 谢谢
> ![GIF](https://user-images.githubusercontent.com/33424662/54470888-ec118000-47ea-11e9-95ed-901a082404ef.gif)

下次提交的时候会加上这个更改。
