### ISSUE TITLE
Bug反馈 弹幕跟随问题

### ISSUE THREAD

**Issue by ShimotsukiH** [CHKZL/DDTV_Old#16]
![image](https://user-images.githubusercontent.com/33424662/54471813-64cc0880-47fa-11e9-95c3-268d9535b834.png)
使用win10的 并排显示窗口功能 会导致弹幕跟随错误的窗口
如图 paryi的弹幕里面出现了夏哥的弹幕……

**Comment by CHKZL** [comment]
最新版本已经解决了这个问题
