### ISSUE TITLE
提需求，建议添加对主站的视频支持

### ISSUE THREAD

**Issue by suzakinishi** [CHKZL/DDTV_Old#18]
虽然这个用不少chrome拓展就能做到，但是多开通常会cpu爆炸

这个监控室试了下资源占用友好多了，方便的话希望增加这个功能

顺带方便的话还是希望能监控油管，毕竟转播man深夜熬不过我担，转播也看不了管的聊天区杂谈回效果会弱不少

**Comment by CHKZL** [comment]
> 虽然这个用不少chrome拓展就能做到，但是多开通常会cpu爆炸
> 
> 这个监控室试了下资源占用友好多了，方便的话希望增加这个功能
> 
> 顺带方便的话还是希望能监控油管，毕竟转播man深夜熬不过我担，转播也看不了管的聊天区杂谈回效果会弱不少

在1.0.2.3版本中已经增加了主站的视频下载支持，播放将在后续版本中添加
在1023版本中同样增加了油管的直播状态查看列表。
