### ISSUE TITLE
已经是新版但是还是提醒要更新

### ISSUE THREAD

**Issue by SekiBetu** [CHKZL/DDTV_Old#19]
![Snipaste_2019-03-17_15-51-34](https://user-images.githubusercontent.com/38283893/54487099-9f9e7100-48cc-11e9-89bd-7c2e5bcaf06c.PNG)
![Snipaste_2019-03-17_15-51-17](https://user-images.githubusercontent.com/38283893/54487101-a1683480-48cc-11e9-9ba8-de0e7a478b18.PNG)

**Comment by CHKZL** [comment]
忘了修改内置版本号标识...马上更新一个增量几百kb的更新，下载替换就行
