### ISSUE TITLE
中文标识符太多了

### ISSUE THREAD

**Issue by xfgryujk** [CHKZL/DDTV_Old#2]
看多了还以为在用易语言...
这样不是不能用编辑器的自动补全吗

**Comment by CHKZL** [comment]
啊....因为这个项目从有想法到最后实现全是摸鱼实现的，还是一边看直播一遍写的..没想到这么多人会需要.，就没按照正式标准来，之后我会逐步修正这个问题。
(另外VS不是支持中文变量\函数名补全么？

**Comment by GongT** [comment]
变量名支持中文是编程语言的巨大进步！（跑

**Comment by xfgryujk** [comment]
切输入法也挺麻烦的

**Comment by CHKZL** [comment]
已经修正了绝大多数
