### ISSUE TITLE
油管下载勾选后再取消勾选窗口变小无法恢复

### ISSUE THREAD

**Issue by SekiBetu** [CHKZL/DDTV_Old#20]
![Snipaste_2019-03-17_15-54-13](https://user-images.githubusercontent.com/38283893/54487139-ff951780-48cc-11e9-963b-946ea5d42952.PNG)
![Snipaste_2019-03-17_15-54-19](https://user-images.githubusercontent.com/38283893/54487141-06238f00-48cd-11e9-99fe-33f101b320ca.PNG)

**Comment by CHKZL** [comment]
emmmm，怀疑是缩放的问题，你的桌面缩放是设置的100%么？

**Comment by SekiBetu** [comment]
WIN10 1809 版本号17763.379  
缩放是125%

**Comment by CHKZL** [comment]
试一试修改为100%看看是否正常？

**Comment by SekiBetu** [comment]
改成100%总不是通用的解决办法，总得想办法解决，甚至是能让窗口缩放也行
一杯茶 一包烟 一个bug改一天
![TIM图片20190317161030](https://user-images.githubusercontent.com/38283893/54487283-50a60b00-48cf-11e9-865b-e6e9021292d2.gif)

**Comment by SekiBetu** [comment]
我先关闭issue了，你慢慢解决wwwwwwwwww

**Comment by CHKZL** [comment]
我悄悄更新了一个，不修改分辨率，默认显示，大约半小时后重新下载一个客户端替换就行了
