### ISSUE TITLE
Release 1.0.1.6a.rar 中含有临时文件夹

### ISSUE THREAD

**Issue by Last-Order** [CHKZL/DDTV_Old#21]
请问为什么`tmp`目录下有一个`4634167_底特律-便乘人类实况① - 犬山玉姬Official _20190317163031.flv`？

不安です

**Comment by CHKZL** [comment]
那是我最后整理打包之前测试下载功能时产生的文件，因为我的问题，最后打包的时候忘记删掉便发布了。
在后续的更新中已经删掉了这类文件。
