### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by cqash** [CHKZL/DDTV_Old#23]
当直播间断流或者其他原因导致推流中断，重新连接后录制会覆盖原来录好的部分导致录像丢失，希望可以先检查有没有同名文件，有的话就重命名什么的

**Comment by CHKZL** [comment]
出现问题的是什么版本的？
在最新的1.0.2.0版本中应该已经解决了这个问题了..

**Comment by Chigusa0w0** [comment]
最新的版本中已经解决了这个问题

**Comment by cqash** [comment]
就是1.0.2.0的版本
今天律和yyut联动的那个被ban之前的录像就没掉了
刚刚犬山那边的更是一个视频文件都没有留下，录像记录里面写着录制完成了，结果只有一个空的文件夹
