### ISSUE TITLE
关于跳转至直播间的问题

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [CHKZL/DDTV_Old#28]
如果房间号包含另一个房间号，点击跳转就会打开两个直播间
![GIF](https://user-images.githubusercontent.com/24391614/55447897-49357000-55f8-11e9-8c67-b6157ce3a1a8.gif)

**Comment by CHKZL** [comment]
问题已经修复。最新本次更新没有推送新版本，如有需要，更新安装即可，我先在留的群号群里测试过没问题，稍候我会提交新的压缩包替换
