### ISSUE TITLE
请教一个Chrome兼容问题

### ISSUE THREAD

**Issue by Colmi** [CHKZL/DDTV_Old#29]
导致Chrome的直播间礼物区、直播动态区无法加载、用户登录无法进行，请问大佬该怎么处理。
![80O4}$67Q2GZW_}60EK1QK](https://user-images.githubusercontent.com/18182259/55566220-d4fce880-572d-11e9-8178-4ce139606482.png)
![MKC5OW13NXV KP导致Chrome的直播间礼物区、直播动态区无法加载、用户登录无法进行，请问大佬该怎么处理。
![80O4}$67Q2GZW_}60EK1QK](https://user-images.githubusercontent.com/18182259/55566220-d4fce880-572d-11e9-8178-4ce139606482.png)
5O5F@8J](https://user-images.githubusercontent.com/18182259/55566271-ecd46c80-572d-11e9-8a1f-ce8ec0ac68ea.png)

**Comment by Colmi** [comment]
补充：该问题可以通过重装Chrome解决，但是原因未知。

**Comment by CHKZL** [comment]
？？？？chrome和我没关系哇.......我根本都和chrome没关系...

**Comment by Chigusa0w0** [comment]
CEF全称Chromium Embedded Framework，还说没关系……

**Comment by CHKZL** [comment]
我是说和电脑上的chrome完全没关系...使用的CEF又没修改电脑上的chrome浏览器..

**Comment by Colmi** [comment]
重新排查了，是另外一个阿B的助手插件的问题，抱歉。
