### ISSUE TITLE
麻烦删掉getUriSteam.cs的106行及相关代码

### ISSUE THREAD

**Issue by zyzsdy** [CHKZL/DDTV_Old#3]
非常感谢你做出这个工具，我最近也有相似的困扰，正在考虑要不要自己动手写一个。
同时我自己写的代码中的一部分可以被其他人用上，起到作用也很开心。

但是复制代码的时候，能不能把这种明显发到我服务器来的统计用代码删一下。
我现在感到很迷惑。

Thanks very much!
お願い申し上げます！

https://github.com/CHKZL/DDTV/blob/eaf8c02c46ced23567bb87d2449619454ac1ad8e/DD%E7%9B%91%E6%8E%A7%E5%AE%A4/getUriSteam.cs#L106

**Comment by CHKZL** [comment]
非常抱歉，因为我没仔细检查，已经删除相关代码，感谢您。
