### ISSUE TITLE
在关闭窗口后，主监控室还可以调整窗口音量

### ISSUE THREAD

**Issue by tiansuojiansan** [CHKZL/DDTV_Old#31]
而在调整之后，程序会停止工作
![无标题](https://user-images.githubusercontent.com/49487123/55886801-f7d04680-5bde-11e9-80ca-9f94603265e2.png)

**Comment by CHKZL** [comment]
在最新的代码状态中已经修复了这个问题，在后续的更新中会推送

**Comment by CHKZL** [comment]
`
 if (VLC[CurrentlyStream].GetPlayerState() == -10)//判断VLC播放器是否被回收
                {
                    return;
                }
                VLC[CurrentlyStream].Volume = trackBar1.Value;//设置音量
                EditTitleVolume(CurrentlyStream, trackBar1.Value);//修改标题音量显示
`
