### ISSUE TITLE
出来挨打

### ISSUE THREAD

**Issue by SekiBetu** [CHKZL/DDTV_Old#32]
![image](https://user-images.githubusercontent.com/38283893/55930197-df017880-5c52-11e9-9ec8-2c1f35fa065d.png)
上图是因为隐藏了config导致我修改路径的时候保存不了
隐藏这些个文件干啥´_＞` 又不是见不得人的东西
只是提个醒´_＞`

**Comment by CHKZL** [comment]
> ![image](https://user-images.githubusercontent.com/38283893/55930197-df017880-5c52-11e9-9ec8-2c1f35fa065d.png)
> 上图是因为隐藏了config导致我修改路径的时候保存不了
> 隐藏这些个文件干啥´_＞` 又不是见不得人的东西 只是提个醒´_＞`

在开发的时候需要频繁删除和修改文件，还有复制最新编译的文件到另外的文件夹进行测试，为了方便就把不会变动的文件隐藏了，最后打包的时候忘了....
最新发布的1.0.2.3a中config文件修改取消了隐藏..
