### ISSUE TITLE
自动录制功能错误

### ISSUE THREAD

**Issue by SekiBetu** [CHKZL/DDTV_Old#34]
![Snipaste_2019-04-18_14-25-16](https://user-images.githubusercontent.com/38283893/56340903-e8a45680-61e5-11e9-9bea-04fdf0a9ecf4.png)
因为美兔没开播，所以错误录制之后立即结束了，没有留下文件

**Comment by CHKZL** [comment]
意思是本来是mea开播，但是提示的阿委开播，并且开启录像么？

**Comment by SekiBetu** [comment]
是的

**Comment by CHKZL** [comment]
了解，我看一看..

**Comment by CHKZL** [comment]
已经修复了这个问题
我替换了1024b的升级补丁和完整包，您只需要下载
https://github.com/CHKZL/DDTV/releases/tag/1.0.2.4b
中那个200多kb的升级补丁替换即可

**Comment by SekiBetu** [comment]
> 已经修复了这个问题
> 我替换了1024b的升级补丁和完整包，您只需要下载
> https://github.com/CHKZL/DDTV/releases/tag/1.0.2.4b
> 中那个200多kb的升级补丁替换即可

顺便一提，用bandizip的7Z格式最大压缩模式可以把231M的完整包压缩成65M，少15M上传的时间，可以试试

**Comment by CHKZL** [comment]
> > 已经修复了这个问题
> > 我替换了1024b的升级补丁和完整包，您只需要下载
> > https://github.com/CHKZL/DDTV/releases/tag/1.0.2.4b
> > 中那个200多kb的升级补丁替换即可
> 
> 顺便一提，用bandizip的7Z格式最大压缩模式可以把231M的完整包压缩成65M，少15M上传的时间，可以试试

之前有一个版本就是使用7Z压缩，结果有很多冲国DD不知道用的什么奇葩解压软件，各种解压错误解压不能，所以就换回用最正常的rar5.0压缩了...
