### ISSUE TITLE
弹幕录制无提醒中断。

### ISSUE THREAD

**Issue by hiruamika** [CHKZL/DDTV_Old#36]
1.0.2.3a没出现过，更新1.0.2.4b后发现偶尔会有视频录制完整而弹幕录制中断的情况，中断时无任何提醒，出现时间在直播开始后20到60分钟不等，同时产生多个只有文件头的空弹幕文件，一旦出现无法通过人工操作恢复，必须重启DDTV。
换回1.0.2.3a暂时没再出现这个问题，虽然同样会产生多个弹幕文件，但每个文件都能完整录制到直播结束。

**Comment by CHKZL** [comment]
找到原因了，在用于获取弹幕数据的函数ReadDanmakuList中如果出现弹幕服务器超时或者返回的数据出现错误，会抛出异常，导致弹幕线程假死。
我会尝试修复这个问题，之后会随着1.0.2.5更新一起推送。

**Comment by hiruamika** [comment]
辛苦了。
