### ISSUE TITLE
关于录制的一些问题

### ISSUE THREAD

**Issue by kokoro223** [CHKZL/DDTV_Old#39]
录制油管的时候，我手动复制进去的频道显示是没有该频道，然后刷新主界面那个youtube频道的就可以直接录制，例子是乙女音的频道

**Comment by CHKZL** [comment]
> 录制油管的时候，我手动复制进去的频道显示是没有该频道，然后刷新主界面那个youtube频道的就可以直接录制，例子是乙女音的频道

"刷新主界面那个youtube频道"指的是哪里？

**Comment by CHKZL** [comment]
> 录制油管的时候，我手动复制进去的频道显示是没有该频道，然后刷新主界面那个youtube频道的就可以直接录制，例子是乙女音的频道

经过测试，oto的油管频道link为：“https://www.youtube.com/channel/UCvEX2UICvFAa_T6pqizC20g”，使用“UCvEX2UICvFAa_T6pqizC20g”进行下载录制并没有出现错误，确定不是使用了直播link或者视频link么？

**Comment by kokoro223** [comment]
我在确实的输入UCvEX2UICvFAa_T6pqizC20g进行下载录制提示是没有该频道，然后关于刷新频道，是在查看正在直播的youtube频道的，如果还有同样情况出现的话，我下次尽可能截图保留下来。

**Comment by CHKZL** [comment]
> 我在确实的输入UCvEX2UICvFAa_T6pqizC20g进行下载录制提示是没有该频道，然后关于刷新频道，是在查看正在直播的youtube频道的，如果还有同样情况出现的话，我下次尽可能截图保留下来。

emmmm，通过描述查看代码，出现这个问题的唯一可能性是“连接到油管服务器失败”，也就是在访问
https://www.youtube.com/channel/UCvEX2UICvFAa_T6pqizC20g/live
时连接超时或者服务器返回404，403等错误
如果确认能连接到谷歌服务器，可以录制一个输入对应频道号下载报错整个过程的GIF么？

**Comment by CHKZL** [comment]
问题已经解决，当选择分辨率高于直播流本身的分辨率时会返回错误的“该频道不存在”。
后续会修复这个问题
