### ISSUE TITLE
添加新的推 对 直播状态有错误的识别

### ISSUE THREAD

**Issue by ShimotsukiH** [CHKZL/DDTV_Old#4]
如图 明明没开播显示开播了
![image](https://user-images.githubusercontent.com/33424662/54254122-87a5b500-458d-11e9-802a-556475721f3e.png)
![image](https://user-images.githubusercontent.com/33424662/54254125-8eccc300-458d-11e9-88af-2a587b8603d6.png)
![image](https://user-images.githubusercontent.com/33424662/54254134-98eec180-458d-11e9-96b9-b640e5407410.png)

**Comment by CHKZL** [comment]
在直播结束后有个五分钟的倒计时，倒计时完了才算下播......这个暂时没找到怎么解决...

**Comment by ShimotsukiH** [comment]
但是我现在添加的这些都没有开轮播啊……

**Comment by CHKZL** [comment]
给一个现在显示错误的，我调试一下看看

**Comment by CHKZL** [comment]
发现问题了，你这是因为输入的房间号错了....
才发布的1.0.1.2中，错误\不存在的房间号不会再显示成正在直播了
