### ISSUE TITLE
确认退出的弹窗不会自动关闭导致卡在关机确认界面

### ISSUE THREAD

**Issue by DayDreamerDD** [CHKZL/DDTV_Old#40]
挂在后台时关机，确认退出的弹窗不会自动关闭，导致一直停留在XX正在阻止关机的界面，需要点仍然关机或者取消关机手动确认退出DDTV后再关机

**Comment by CHKZL** [comment]
后续代码中会增加检测系统关机事件的代码，如果检测到关机事件，直接执行关闭不弹出会堵塞系统关机的提示窗。

**Comment by CHKZL** [comment]
在1.0.2.6更新中已经修复了这个问题
