### ISSUE TITLE
希望能添加单独的弹幕录制功能。

### ISSUE THREAD

**Issue by hiruamika** [CHKZL/DDTV_Old#41]
希望能添加单独的b站弹幕录制功能，即不录制视频仅录制弹幕，无论直播间是否开播均持续对弹幕进行实时录制。（或者单独发布一个弹幕录制版本可能更好？）
另外1026仍有弹幕录制中断的情况，目前弹幕录制还是在用1023。

**Comment by CHKZL** [comment]
这个功能可以搞，顺便...1023和1026的弹幕录制应该是使用的同样的代码才对....

**Comment by hiruamika** [comment]
1023用了两星期左右，除了崩溃的场合，弹幕录制中断的情况一次都没出现过，信号不好或直播中断时会额外产生零碎的弹幕文件，不过最先产生的那个都能稳定录完。
同样的情况1026也会产生新的弹幕文件，但最初的弹幕文件大概率直接中断，同时还有视频流完整而弹幕无提醒中断的情况，并且新产生的弹幕文件只有文件头（前三行）而不写入任何弹幕，不重启的话就算重新开始录制视频，弹幕录制功能也无法恢复。

**Comment by CHKZL** [comment]
> 1023用了两星期左右，除了崩溃的场合，弹幕录制中断的情况一次都没出现过，信号不好或直播中断时会额外产生零碎的弹幕文件，不过最先产生的那个都能稳定录完。
> 同样的情况1026也会产生新的弹幕文件，但最初的弹幕文件大概率直接中断，同时还有视频流完整而弹幕无提醒中断的情况，并且新产生的弹幕文件只有文件头（前三行）而不写入任何弹幕，不重启的话就算重新开始录制视频，弹幕录制功能也无法恢复。

接下来我重审一下弹幕录制的代码，尝试修复这个问题，并且在下个版本中单独增加弹幕录制功能

**Comment by hiruamika** [comment]
感谢，辛苦了。
