### ISSUE TITLE
1026莫名崩溃

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [CHKZL/DDTV_Old#43]
运行了一段时间后会在无提示的情况下崩溃，事件管理器记录为内存溢出
![ddtvbug](https://user-images.githubusercontent.com/44915585/57976900-2206f680-7a1e-11e9-9618-749c4e3b6422.png)

**Comment by CHKZL** [comment]
我尽量复现了一下，发现是因为弹幕功能所依赖的CEF框架所造成了，并且这个优化难度极大。
接下来我打算把内容功能全部分离开，功能之间进程独立，这样观看直播功能挂掉了不会影响到下载和其他功能。
(ps.最近这段时间我在忙着换工作，可能这个进度会慢一点..

**Comment by SaltyFishOnTheSea** [comment]
> 我尽量复现了一下，发现是因为弹幕功能所依赖的CEF框架所造成了，并且这个优化难度极大。
> 接下来我打算把内容功能全部分离开，功能之间进程独立，这样观看直播功能挂掉了不会影响到下载和其他功能。
> (ps.最近这段时间我在忙着换工作，可能这个进度会慢一点..

慢慢来吧，我已经习惯定时重启防崩溃了

**Comment by CHKZL** [comment]
进过多次重现，发现只有在硬件压力(特别是CPU)高的时候，开着弹幕功能，把窗口全屏，会大概率触发这个BUG，其他情况下暂时还没发现。

**Comment by SaltyFishOnTheSea** [comment]
> 进过多次重现，发现只有在硬件压力(特别是CPU)高的时候，开着弹幕功能，把窗口全屏，会大概率触发这个BUG，其他情况下暂时还没发现。

我是开了三四个后台录制，没有开任何弹幕和直播窗口，然后会在cpu70%左右概率性崩溃，挂的时间越久崩溃的机率越高

**Comment by CHKZL** [comment]
emmmm，这个可能是因为弹幕功能实际内存回收机制错误导致的，也就是每一个录制完成时，同步进行弹幕录制的子线程没有被回收，累积起来导致的内存溢出，之前有人给我说了这个问题，我本地代码里也修复了但还未发布，如果可以可以加入我在README.md里写的那个Q群号联系我，我把这个版本单独打包升级补丁给你先使用。(如果可以反馈一下效果就更好了)

**Comment by CHKZL** [comment]
> > 进过多次重现，发现只有在硬件压力(特别是CPU)高的时候，开着弹幕功能，把窗口全屏，会大概率触发这个BUG，其他情况下暂时还没发现。
> 
> 我是开了三四个后台录制，没有开任何弹幕和直播窗口，然后会在cpu70%左右概率性崩溃，挂的时间越久崩溃的机率越高

https://github.com/CHKZL/DDTV/releases/download/1.0.2.6/1.0.2.6_p1.rar
下载这个补丁覆盖替换文件就行了，修复了弹幕显示和录制功能造成的内存溢出问题。

**Comment by SaltyFishOnTheSea** [comment]
> > > 进过多次重现，发现只有在硬件压力(特别是CPU)高的时候，开着弹幕功能，把窗口全屏，会大概率触发这个BUG，其他情况下暂时还没发现。
> > 
> > 
> > 我是开了三四个后台录制，没有开任何弹幕和直播窗口，然后会在cpu70%左右概率性崩溃，挂的时间越久崩溃的机率越高
> 
> https://github.com/CHKZL/DDTV/releases/download/1.0.2.6/1.0.2.6_p1.rar
> 下载这个补丁覆盖替换文件就行了，修复了弹幕显示和录制功能造成的内存溢出问题。

暂时没有问题了
