### ISSUE TITLE
建议添加功能：关闭直播窗口后继续自动录屏

### ISSUE THREAD

**Issue by banana-suisei** [CHKZL/DDTV_Old#47]
如题

**Comment by CHKZL** [comment]
> 如题

DDTV1.0已经停止维护了，现在已经是DDTV2.0时代了((
请移步至[https://github.com/CHKZL/DDTV2](DDTV2)

**Comment by CHKZL** [comment]
> 如题

DDTV1.0已经停止维护了，现在已经是DDTV2.0时代了((
请移步至[DDTV2](https://github.com/CHKZL/DDTV2)
