### ISSUE TITLE
功能需求：录制中的节目状态里能显示录制中

### ISSUE THREAD

**Issue by ntlf9t** [CHKZL/DDTV_Old#49]
功能需求：录制中的节目状态里能显示录制中，有时候开播了DDTV并没有自动录制，丢了好多经常瞬间( Ĭ ^ Ĭ )

**Comment by CHKZL** [comment]
本项目已经停止更新，后续的开发全部转移到DDTV2项目中，并且在DDTV2中该功能已经实现了

https://github.com/CHKZL/DDTV2
