### ISSUE TITLE
您好，提个建议

### ISSUE THREAD

**Issue by Mayuker** [CHKZL/DDTV_Old#5]
可以考虑加入刷新功能吗？

**Comment by ol416** [comment]
![chrome_2019-03-13_15-28-39](https://user-images.githubusercontent.com/26591299/54260781-e6c2f400-45a4-11e9-87ec-e528caef091e.png)
这个不是**刷新直播状态**的吗？

**Comment by ShimotsukiH** [comment]
他的意思可能是说直播窗口刷新？

**Comment by Mayuker** [comment]
。。。不好意思。表达的不好，如楼上所说的是直播窗口刷新

**Comment by LzNOHentai** [comment]
直播窗口刷新+1

**Comment by CHKZL** [comment]
在1.0.1.2更新里的这个功能已经安排上的了
选中窗口按F5刷新((
