### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by LzNOHentai** [CHKZL/DDTV_Old#6]
1.如另一个Issue所述，希望加入直播间窗口刷新功能。
2.不知道现在默认获取的是什么画质？希望加入直播画质的切换功能。
3.希望能够将当前正在直播的直播间自动置顶，摸鱼的直播间再按原先的顺序排列。

4.以下DD：因为直播间太多，所以能够添加一个自定义折叠列表的功能就好了，这样就可以按箱收纳……

**Comment by CHKZL** [comment]
emmmm，其实增加一个正在直播的房间自动置顶功能是不是就不是很需要收纳箱了？

**Comment by LzNOHentai** [comment]
> emmmm，其实增加一个正在直播的房间自动置顶功能是不是就不是很需要收纳箱了？

确实，这个功能不是很必要就是了，毕竟不是每个人都看那么多到需要按箱收纳。
只是因为箱推后确实太多了，整个列表字又小就显得很杂乱，如果需要编辑找起来也不是很方便。

那或者能否考虑一下把列表的行间距和字体大小之类的调整一下？稍微易看一些。
顺便，如果能够可以允许编辑排列顺序就好了。

**Comment by CHKZL** [comment]
最新的版本已经加上了，正在直播的房间会显示在最上面
