### ISSUE TITLE
建议增加功能：下载推流

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [CHKZL/DDTV_Old#7]
不需要内置下载功能，只需要把提取到的推流地址发给别的下载软件（浏览器/迅雷/fdm/aria2之类）

**Comment by Etherrrr** [comment]
上述的下载软件应该均不支持直播流的下载，需要下载录制直播流的话推荐使用ffmpeg或[streamlink](https://github.com/streamlink/streamlink)等支持流媒体录制的工具。
获取推流地址的话也有现成轮子，如[live-stream-recorder](https://github.com/printempw/live-stream-recorder)和[Minyami](https://github.com/printempw/live-stream-recorder)

**Comment by Road-To-Gensokyo** [comment]
至少用chrome插件或者检查元素都可以找到b站直播流的地址，然后直接将地址复制到fdm就可以下载flv文件
![QQ截图20190314164447](https://user-images.githubusercontent.com/24391614/54342880-87361880-4678-11e9-97e2-75d3820296c9.png)
